// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	postmand "github.com/allisson/postmand"
	mock "github.com/stretchr/testify/mock"
)

// DeliveryAttemptService is an autogenerated mock type for the DeliveryAttemptService type
type DeliveryAttemptService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, getOptions
func (_m *DeliveryAttemptService) Get(ctx context.Context, getOptions postmand.RepositoryGetOptions) (*postmand.DeliveryAttempt, error) {
	ret := _m.Called(ctx, getOptions)

	var r0 *postmand.DeliveryAttempt
	if rf, ok := ret.Get(0).(func(context.Context, postmand.RepositoryGetOptions) *postmand.DeliveryAttempt); ok {
		r0 = rf(ctx, getOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postmand.DeliveryAttempt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, postmand.RepositoryGetOptions) error); ok {
		r1 = rf(ctx, getOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, listOptions
func (_m *DeliveryAttemptService) List(ctx context.Context, listOptions postmand.RepositoryListOptions) ([]*postmand.DeliveryAttempt, error) {
	ret := _m.Called(ctx, listOptions)

	var r0 []*postmand.DeliveryAttempt
	if rf, ok := ret.Get(0).(func(context.Context, postmand.RepositoryListOptions) []*postmand.DeliveryAttempt); ok {
		r0 = rf(ctx, listOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*postmand.DeliveryAttempt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, postmand.RepositoryListOptions) error); ok {
		r1 = rf(ctx, listOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
