// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	postmand "github.com/allisson/postmand"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DeliveryRepository is an autogenerated mock type for the DeliveryRepository type
type DeliveryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, delivery
func (_m *DeliveryRepository) Create(ctx context.Context, delivery *postmand.Delivery) error {
	ret := _m.Called(ctx, delivery)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *postmand.Delivery) error); ok {
		r0 = rf(ctx, delivery)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DeliveryRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dispatch provides a mock function with given fields: ctx
func (_m *DeliveryRepository) Dispatch(ctx context.Context) (*postmand.DeliveryAttempt, error) {
	ret := _m.Called(ctx)

	var r0 *postmand.DeliveryAttempt
	if rf, ok := ret.Get(0).(func(context.Context) *postmand.DeliveryAttempt); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postmand.DeliveryAttempt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, getOptions
func (_m *DeliveryRepository) Get(ctx context.Context, getOptions postmand.RepositoryGetOptions) (*postmand.Delivery, error) {
	ret := _m.Called(ctx, getOptions)

	var r0 *postmand.Delivery
	if rf, ok := ret.Get(0).(func(context.Context, postmand.RepositoryGetOptions) *postmand.Delivery); ok {
		r0 = rf(ctx, getOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postmand.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, postmand.RepositoryGetOptions) error); ok {
		r1 = rf(ctx, getOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, listOptions
func (_m *DeliveryRepository) List(ctx context.Context, listOptions postmand.RepositoryListOptions) ([]*postmand.Delivery, error) {
	ret := _m.Called(ctx, listOptions)

	var r0 []*postmand.Delivery
	if rf, ok := ret.Get(0).(func(context.Context, postmand.RepositoryListOptions) []*postmand.Delivery); ok {
		r0 = rf(ctx, listOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*postmand.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, postmand.RepositoryListOptions) error); ok {
		r1 = rf(ctx, listOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, delivery
func (_m *DeliveryRepository) Update(ctx context.Context, delivery *postmand.Delivery) error {
	ret := _m.Called(ctx, delivery)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *postmand.Delivery) error); ok {
		r0 = rf(ctx, delivery)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
